theme: jekyll-theme-cayman
title: GTT REST API
description: La VERA API dei trasporti pubblici nascosta di GTT
show_jar_downloads: true
github: 
  jar_url: https://github.com/Gabboxl/gtt-api-keygen/releases/download/v1.0.0/gtt-keygen.jar
